version: '3.8'

services:
  news-scraper:
    build:
      context: ./news-scraper
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    volumes:
      - ./news-scraper:/app
    environment:
      - FLASK_ENV=development
    networks:
      - mse-scraper-network

  nlp:
    build:
      context: ./nlp
      dockerfile: Dockerfile
    ports:
      - "5004:5000"
    volumes:
      - ./nlp:/app
    environment:
      - FLASK_ENV=development
    networks:
      - mse-scraper-network
  indicators:
    build:
      context: ./indicators-service
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    volumes:
      - ./indicators-service:/app
    environment:
      - FLASK_ENV=development
    networks:
      - mse-scraper-network
networks:
  mse-scraper-network:
    driver: bridge
